### ISSUE TITLE
Phar autoloader cannot find class Symfony\Component\Process\ExecutableFinder;

### ISSUE THREAD

**Issue by codeguy** [enlightn/security-checker#24]
Downloaded latest phar file. Attempting to execute with `php ./security-checker.phar security:check ./composer.lock --no-dev --temp-dir=/tmp`. It fails with message:

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ExecutableFinder' not found in phar:///apps/foobar/security-checker.phar/src/ZipExtractor.php:39
Stack trace:
#0 phar:///apps/foobar/security-checker.phar/src/ZipExtractor.php(19): Enlightn\SecurityChecker\ZipExtractor->unzipCommandExists()
#1 phar:///apps/foobar/security-checker.phar/src/AdvisoryFetcher.php(44): Enlightn\SecurityChecker\ZipExtractor->extract()
#2 phar:///apps/foobar/security-checker.phar/src/SecurityChecker.php(25): Enlightn\SecurityChecker\AdvisoryFetcher->fetchAdvisories()
#3 phar:///apps/foobar/security-checker.phar/src/SecurityCheckerCommand.php(64): Enlightn\SecurityChecker\SecurityChecker->check()
#4 phar:///apps/foobar/security-checker.phar/vendor/symfony/console/Command/Command.php(256): Enlightn\SecurityChecker\SecurityCheckerCommand->execute()
#5 phar:///apps/foobar/security-checker.phar/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#6 phar:///apps/foobar/security-checker.phar/vendor/symfony/console/Applicatio in phar:///apps/rti/security-checker.phar/src/ZipExtractor.php on line 39
```

Source OS is Ubuntu 20.04LTS. Local PHP cli version is:

```
PHP 7.4.21 (cli) (built: Jul  1 2021 16:09:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies
```

Tested with and without Ubuntu `unzip` package installed.
Thoughts?

**Comment by codeguy** [comment]
I do have the PHP zip extension installed.

**Comment by codeguy** [comment]
Works fine as a global or per-project composer install. Just the phar appears to be busted.

**Comment by paras-malhotra** [comment]
This should be fixed now
